### PR TITLE
Remove duplicated file in pkg/tcpip/link/rawfile.

### PR DESCRIPTION
**Pull request by xiaobo55x**
The blockingpoll_unsafe.go was copied to blockingpoll_noyield_unsafe.go
during merging commit 7206202bb9439499. If it still stay here, it would
cause build errors on non-amd64 platform.

ERROR:
pkg/tcpip/link/rawfile/BUILD:5:1:
GoCompilePkg
pkg/tcpip/link/rawfile.a
failed (Exit 1) builder failed: error executing command
bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk
external/go_sdk -installsuffix linux_arm64 -src
pkg/tcpip/link/rawfile/blockingpoll_noyield_unsafe.go -src ...
(remaining 33 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
compilepkg: error running subcommand: exit status 2
pkg/tcpip/link/rawfile/blockingpoll_yield_unsafe.go:35:6:
BlockingPoll redeclared in this block
        previous declaration at
pkg/tcpip/link/rawfile/blockingpoll_unsafe.go:26:78
Target //pkg/tcpip/link/rawfile:rawfile failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 25.531s, Critical Path: 21.08s
INFO: 262 processes: 262 linux-sandbox.
FAILED: Build did NOT complete successfully

Signed-off-by: Haibo Xu <haibo.xu@arm.com>
Change-Id: I4e21f82984225d0aa173de456f7a7c66053a053e

### CODE REVIEW

**Comment by xiaobo55x** [comment]
Hi @hbhasker,

This patch is to fix a issue introduced in #722. Please help have a review!

Regards,
Haibo

**Comment by xiaobo55x** [comment]
Hi @hbhasker,

The kokoro run check can't pass due to 1 one 104 tests failed. According to the test logs, it seems that the runsc was not able to open the /dev/kvm for read/write. Could you help have a look?

```
==================== Test output for //pkg/sentry/platform/kvm:kvm_test:
--- FAIL: TestKernelSyscall (0.00s)
    kvm_test.go:44: error opening device file: error opening /dev/kvm: open /dev/kvm: permission denied
--- FAIL: TestKernelFault (0.00s)
    kvm_test.go:44: error opening device file: error opening /dev/kvm: open /dev/kvm: permission denied
--- FAIL: TestKernelFloatingPoint (0.00s)
    kvm_test.go:44: error opening device file: error opening /dev/kvm: open /dev/kvm: permission denied
--- FAIL: TestApplicationSyscall (0.00s)
    kvm_test.go:44: error opening device file: error opening /dev/kvm: open /dev/kvm: permission denied
--- FAIL: TestApplicationFault (0.00s)
    kvm_test.go:44: error opening device file: error opening /dev/kvm: open /dev/kvm: permission denied
--- FAIL: TestRegistersSyscall (0.00s)
    kvm_test.go:44: error opening device file: error opening /dev/kvm: open /dev/kvm: permission denied
--- FAIL: TestRegistersFault (0.00s)
    kvm_test.go:44: error opening device file: error opening /dev/kvm: open /dev/kvm: permission denied
--- FAIL: TestSegments (0.00s)
    kvm_test.go:44: error opening device file: error opening /dev/kvm: open /dev/kvm: permission denied
--- FAIL: TestBounce (0.00s)
    kvm_test.go:44: error opening device file: error opening /dev/kvm: open /dev/kvm: permission denied
--- FAIL: TestBounceStress (0.00s)
    kvm_test.go:44: error opening device file: error opening /dev/kvm: open /dev/kvm: permission denied
--- FAIL: TestInvalidate (0.00s)
    kvm_test.go:44: error opening device file: error opening /dev/kvm: open /dev/kvm: permission denied
--- FAIL: TestEmptyAddressSpace (0.00s)
    kvm_test.go:44: error opening device file: error opening /dev/kvm: open /dev/kvm: permission denied
--- FAIL: TestWrongVCPU (0.00s)
    kvm_test.go:44: error opening device file: error opening /dev/kvm: open /dev/kvm: permission denied
```


Regards,
Haibo

**Comment by xiaobo55x** [comment]
@hbhasker, Thanks!
